- hosts: unity
  vars:
    user: "admin"
    password: "Password1234#"
  tasks:
    - name: Authenticate & retrieve cookie
      uri:
        method: GET
        headers:
          "x-emc-rest-client": "TRUE"
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
        url: https://{{inventory_hostname}}/api/types/pool/instances?compact=true&fields=id%2Cname
      register: result

    - name: DEBUG / GOT Login INFO
      debug:
        msg: "{{ result }}"

    - name: Set Pool ID fact
      set_fact:
        pool_id: "{{ result.json.entries[0].content.id }}"

    - name: Print Pool ID
      debug:
        msg: "{{ pool_id }}"

    - name: Print Pool ID
      debug:
        msg: "{{ pool_id }}"

    - name: Get Lun ID
      uri:
        method: GET
        headers:
          "x-emc-rest-client": "TRUE"
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
        url: https://{{inventory_hostname}}/api/types/lun/instances?compact=true&fields=id%2Cname
      register: lun_id

    - name: DEBUG / GOT Login INFO
      debug:
        msg: "{{ lun_id }}"

    - name: Lun ID's are
      debug:
        msg: "{{ lun_id }}"

    - name: Dynamically update the pool ID in lundetails.txt file
      template:
        src: ./lundetails.txt
        dest: ./lundetails.txt
   
    - name: Create Pool
      uri:
        url: https://{{inventory_hostname}}/api/types/storageResource/action/createLun
        method: POST
        body: "{{ lookup('file','lundetails.txt', convert_data=False)}}"
        body_format: json
        http_agent: Ansible
        remote_src: no
        follow_redirects: yes
        validate_certs: no
        return_content: yes
        force: yes
        status_code: 201,422
        headers:
          cookie: "{{ result.cookies|dictsort(false)|map('join', '=')|join('; ') }}"
          Content-type: application/json
          Accept: application/json
          EMC-CSRF-TOKEN: "{{ result.emc_csrf_token }}"
          X-EMC-REST-CLIENT: true
      register: lun_create_result
    - name: DEBUG / GOT lun_create_result  INFO
      debug:
          msg: "{{lun_create_result }}"
