---
# tasks file for auth
    - name: Authenticate & retrieve cookie
      uri:
        method: GET
        headers:
          "x-emc-rest-client": "TRUE"
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        url: https://{{inventory_hostname}}/api/types/loginSessionInfo/instances
        validate_certs: no
      register: result
    - name: DEBUG / GOT Login INFO
      debug:
          msg: "{{ result }}"
