---
# tasks file for Logout
    - name: Logout user
      uri:
        url: https://{{inventory_hostname}}/api/types/loginSessionInfo/action/logout
        method: POST
        body_format: json
        http_agent: Ansible
        remote_src: no
        follow_redirects: yes
        validate_certs: no
        return_content: yes
        force: yes
        headers:
          cookie: "{{ result.cookies|dictsort(false)|map('join', '=')|join('; ') }}"
          Content-type: application/json
          Accept: application/json
          EMC-CSRF-TOKEN: "{{ result.emc_csrf_token }}"
          X-EMC-REST-CLIENT: true
      register: logout
    - name: DEBUG / GOT logout  INFO
      debug:
          msg: "{{logout }}"

